# Generated by Django 5.0.4 on 2024-04-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advertisement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisementimages",
            name="image",
            field=models.BinaryField(verbose_name="Image"),
        ),
    ]
